package orchestrator

import (
	"io"
	"log/slog"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	forgeconfig "github.com/aholstenson/kvarn/internal/config/forge"
)

func quietLogger() *slog.Logger {
	return slog.New(slog.NewTextHandler(io.Discard, nil))
}

func boolPtr(v bool) *bool { return &v }

var _ = Describe("withLegacyReporting", func() {
	It("leaves the block alone when it sets both toggles", func() {
		out := withLegacyReporting(
			forgeconfig.PRContent{ReportWorklog: boolPtr(true), ReportCost: boolPtr(true)},
			boolPtr(false), boolPtr(false), quietLogger(), "somewhere")

		Expect(*out.ReportWorklog).To(BeTrue(), "the block wins over the superseded spelling")
		Expect(*out.ReportCost).To(BeTrue())
	})

	It("falls back to the superseded top-level spelling", func() {
		out := withLegacyReporting(forgeconfig.PRContent{},
			boolPtr(false), boolPtr(false), quietLogger(), "somewhere")

		Expect(*out.ReportWorklog).To(BeFalse())
		Expect(*out.ReportCost).To(BeFalse())
	})

	It("resolves each toggle on its own", func() {
		out := withLegacyReporting(
			forgeconfig.PRContent{ReportWorklog: boolPtr(true)},
			boolPtr(false), boolPtr(false), quietLogger(), "somewhere")

		Expect(*out.ReportWorklog).To(BeTrue())
		Expect(*out.ReportCost).To(BeFalse())
	})

	It("leaves both unset when neither spelling is configured", func() {
		out := withLegacyReporting(forgeconfig.PRContent{}, nil, nil, quietLogger(), "somewhere")
		Expect(out.ReportWorklog).To(BeNil(), "an unset toggle must still inherit the next layer down")
		Expect(out.ReportCost).To(BeNil())
	})
})

var _ = Describe("renderPRTemplate", func() {
	data := prTemplateData{
		Title:       "fix: handle retries",
		Description: "Body text.",
		SessionID:   "abc123",
		Branch:      "kvarn/handle-retries-abc123",
		Mode:        "fix",
	}

	It("expands the run's identity", func() {
		Expect(renderPRTemplate("kvarn · session {{ .SessionID }} · {{ .Mode }}", data, quietLogger())).To(
			Equal("kvarn · session abc123 · fix"))
	})

	It("passes plain text through untouched", func() {
		Expect(renderPRTemplate("Generated by kvarn", data, quietLogger())).To(Equal("Generated by kvarn"))
	})

	It("returns nothing for an empty template", func() {
		Expect(renderPRTemplate("", data, quietLogger())).To(BeEmpty())
	})

	It("drops a template that does not parse rather than publishing the braces", func() {
		Expect(renderPRTemplate("session {{ .SessionID", data, quietLogger())).To(BeEmpty())
	})

	It("drops a template naming a field that does not exist", func() {
		Expect(renderPRTemplate("{{ .NoSuchField }}", data, quietLogger())).To(BeEmpty())
	})

	Describe("renderPRTemplates", func() {
		It("keeps the ones that render and drops the ones that do not", func() {
			out := renderPRTemplates([]string{
				"Kvarn-Session: {{ .SessionID }}",
				"Broken: {{ .Nope }}",
				"Kvarn-Mode: {{ .Mode }}",
			}, data, quietLogger())

			Expect(out).To(Equal([]string{"Kvarn-Session: abc123", "Kvarn-Mode: fix"}))
		})
	})
})
