package orchestrator

import (
	"io"
	"log/slog"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	forgeconfig "github.com/aholstenson/kvarn/internal/config/forge"
)

func quietLogger() *slog.Logger {
	return slog.New(slog.NewTextHandler(io.Discard, nil))
}

func boolPtr(v bool) *bool { return &v }

var _ = Describe("withLegacyReporting", func() {
	It("leaves the block alone when it sets both toggles", func() {
		out := withLegacyReporting(
			forgeconfig.PRContent{ReportWorklog: boolPtr(true), ReportCost: boolPtr(true)},
			boolPtr(false), boolPtr(false), quietLogger(), "somewhere")

		Expect(*out.ReportWorklog).To(BeTrue(), "the block wins over the superseded spelling")
		Expect(*out.ReportCost).To(BeTrue())
	})

	It("falls back to the superseded top-level spelling", func() {
		out := withLegacyReporting(forgeconfig.PRContent{},
			boolPtr(false), boolPtr(false), quietLogger(), "somewhere")

		Expect(*out.ReportWorklog).To(BeFalse())
		Expect(*out.ReportCost).To(BeFalse())
	})

	It("resolves each toggle on its own", func() {
		out := withLegacyReporting(
			forgeconfig.PRContent{ReportWorklog: boolPtr(true)},
			boolPtr(false), boolPtr(false), quietLogger(), "somewhere")

		Expect(*out.ReportWorklog).To(BeTrue())
		Expect(*out.ReportCost).To(BeFalse())
	})

	It("leaves both unset when neither spelling is configured", func() {
		out := withLegacyReporting(forgeconfig.PRContent{}, nil, nil, quietLogger(), "somewhere")
		Expect(out.ReportWorklog).To(BeNil(), "an unset toggle must still inherit the next layer down")
		Expect(out.ReportCost).To(BeNil())
	})
})

var _ = Describe("renderPRTemplate", func() {
	data := prTemplateData{
		Title:       "fix: handle retries",
		Description: "Body text.",
		SessionID:   "abc123",
		Branch:      "kvarn/handle-retries-abc123",
		Mode:        "fix",
		Metadata:    map[string]string{"issue_id": "ENG-42", "jira-key": "AB-1"},
	}

	It("expands the run's identity", func() {
		Expect(renderPRTemplate("kvarn · session {{ .SessionID }} · {{ .Mode }}", data, missingKeyError, quietLogger())).To(
			Equal("kvarn · session abc123 · fix"))
	})

	It("passes plain text through untouched", func() {
		Expect(renderPRTemplate("Generated by kvarn", data, missingKeyError, quietLogger())).To(Equal("Generated by kvarn"))
	})

	It("returns nothing for an empty template", func() {
		Expect(renderPRTemplate("", data, missingKeyError, quietLogger())).To(BeEmpty())
	})

	It("drops a template that does not parse rather than publishing the braces", func() {
		Expect(renderPRTemplate("session {{ .SessionID", data, missingKeyError, quietLogger())).To(BeEmpty())
	})

	It("drops a template naming a field that does not exist", func() {
		Expect(renderPRTemplate("{{ .NoSuchField }}", data, missingKeyError, quietLogger())).To(BeEmpty())
	})

	It("drops a template naming a field that does not exist under either mode", func() {
		Expect(renderPRTemplate("{{ .NoSuchField }}", data, missingKeyZero, quietLogger())).To(BeEmpty(),
			"the missing-key mode governs map keys only; a misspelled field is always a config error")
	})

	Describe("submission metadata", func() {
		It("reads a key through the field syntax", func() {
			Expect(renderPRTemplate("Issue: {{ .Metadata.issue_id }}", data, missingKeyZero, quietLogger())).To(
				Equal("Issue: ENG-42"))
		})

		It("reads a key that the field syntax cannot spell through index", func() {
			Expect(renderPRTemplate(`Jira: {{ index .Metadata "jira-key" }}`, data, missingKeyZero, quietLogger())).To(
				Equal("Jira: AB-1"))
		})

		It("drops a template spelling a hyphenated key as a field", func() {
			Expect(renderPRTemplate("{{ .Metadata.jira-key }}", data, missingKeyZero, quietLogger())).To(BeEmpty(),
				"the template does not parse, so there is nothing to publish")
		})

		It("lets a guard skip a key the submission did not carry", func() {
			tmpl := "{{ with .Metadata.issue_id }}Issue: {{ . }}{{ end }}"
			Expect(renderPRTemplate(tmpl, data, missingKeyZero, quietLogger())).To(Equal("Issue: ENG-42"))
			Expect(renderPRTemplate(tmpl, prTemplateData{}, missingKeyZero, quietLogger())).To(BeEmpty(),
				"a nil metadata map has to render as an absent key, not as a failure")
		})

		It("fails the guard under the strict mode, which is why headers do not use it", func() {
			Expect(renderPRTemplate("{{ if .Metadata.issue_id }}x{{ end }}",
				prTemplateData{}, missingKeyError, quietLogger())).To(BeEmpty())
		})

		It("drops a trailer naming a key the submission did not carry", func() {
			Expect(renderPRTemplate("Issue-Id: {{ .Metadata.nope }}", data, missingKeyError, quietLogger())).To(BeEmpty(),
				"a trailer with nothing after the colon would be committed to history")
		})

		It("renders an absent key as empty under the lenient mode", func() {
			Expect(renderPRTemplate("Issue: {{ .Metadata.nope }}", data, missingKeyZero, quietLogger())).To(
				Equal("Issue: "))
		})
	})

	Describe("preview addresses", func() {
		linked := data.withPreviewLinks(previewLinks{
			Primary: "https://pr-42.preview.example.com",
			Sites: map[string]string{
				"web": "https://pr-42.preview.example.com",
				"api": "https://api-pr-42.preview.example.com",
			},
		})

		It("links the preview a run produced", func() {
			Expect(renderPRTemplate("Preview: {{ .PreviewURL }}", linked, missingKeyZero, quietLogger())).To(
				Equal("Preview: https://pr-42.preview.example.com"))
		})

		It("names one site in particular", func() {
			Expect(renderPRTemplate(`API: {{ index .PreviewURLs "api" }}`, linked, missingKeyZero, quietLogger())).To(
				Equal("API: https://api-pr-42.preview.example.com"))
		})

		It("lets a guard skip a run that has no preview", func() {
			tmpl := "{{ with .PreviewURL }}Preview: {{ . }}{{ end }}"
			Expect(renderPRTemplate(tmpl, linked, missingKeyZero, quietLogger())).To(
				Equal("Preview: https://pr-42.preview.example.com"))
			Expect(renderPRTemplate(tmpl, data, missingKeyZero, quietLogger())).To(BeEmpty(),
				"a run with no address to link has to render as absent, not as a failure")
		})

		It("lets a guard skip a site this repository does not declare", func() {
			tmpl := `{{ with index .PreviewURLs "docs" }}Docs: {{ . }}{{ end }}`
			Expect(renderPRTemplate(tmpl, linked, missingKeyZero, quietLogger())).To(BeEmpty())
			Expect(renderPRTemplate(tmpl, data, missingKeyZero, quietLogger())).To(BeEmpty(),
				"a nil site map reads as a site nobody declared")
		})
	})

	Describe("renderPRTemplates", func() {
		It("keeps the ones that render and drops the ones that do not", func() {
			out := renderPRTemplates([]string{
				"Kvarn-Session: {{ .SessionID }}",
				"Broken: {{ .Nope }}",
				"Kvarn-Mode: {{ .Mode }}",
			}, data, missingKeyError, quietLogger())

			Expect(out).To(Equal([]string{"Kvarn-Session: abc123", "Kvarn-Mode: fix"}))
		})
	})
})
