package coding

import (
	"fmt"
	"strings"
	"unicode"

	forgeconfig "github.com/aholstenson/kvarn/internal/config/forge"
)

// notProvided stands in for a required section the agent left empty even after
// being asked again. The section is rendered rather than dropped so a reviewer
// sees the gap instead of a body that looks complete.
const notProvided = "_(not provided)_"

// summarySystemPrompt builds the system prompt for the summary call: who is
// writing, whose conventions apply, and the repository's own instruction file
// as a last resort for conventions nobody stated explicitly.
//
// Configured instructions are labelled by origin. An operator's house style and
// a repository's local rules are both in force, and when they pull in different
// directions the model can at least see which is which.
func summarySystemPrompt(content forgeconfig.Content, repoInstructions string) string {
	var sb strings.Builder
	sb.WriteString("You are a technical writer producing a commit message and pull request description for work that was just completed.")

	writeInstructionBlock(&sb, "Organization conventions", content.TitleInstructions.Organization,
		content.BodyInstructions.Organization)
	writeInstructionBlock(&sb, "Repository conventions", content.TitleInstructions.Repository,
		content.BodyInstructions.Repository)

	if repoInstructions != "" {
		sb.WriteString("\n\nThe following project instructions may contain commit message conventions you should follow:\n\n")
		sb.WriteString(repoInstructions)
	}
	return sb.String()
}

// writeInstructionBlock appends one labelled instruction section, skipping it
// when every part is empty.
func writeInstructionBlock(sb *strings.Builder, heading string, parts ...string) {
	var kept []string
	for _, p := range parts {
		if p = strings.TrimSpace(p); p != "" {
			kept = append(kept, p)
		}
	}
	if len(kept) == 0 {
		return
	}
	fmt.Fprintf(sb, "\n\n## %s\n\n", heading)
	sb.WriteString(strings.Join(kept, "\n\n"))
}

// summaryPrompt is the trailing user turn that asks for the commit/PR summary.
// The footer prohibition is deliberate: a run's identity footer and commit
// trailers are appended by kvarn after the fact, where they are exact, so a
// model-written one would only duplicate them.
func summaryPrompt(content forgeconfig.Content, recentCommits []string) string {
	var sb strings.Builder
	sb.WriteString("Summarize the work you just completed for a git commit and pull request.\n\n")
	sb.WriteString("Provide, in this order:\n")
	sb.WriteString("- description: a commit body suitable as both the commit message body and the PR description. " +
		"Write a few short paragraphs in past tense explaining what changed and why. Wrap lines at ~72 chars. " +
		"Do not repeat the title. Do not list every file touched. " +
		"Do not add a footer such as \"Generated by\" or a session id.\n")

	if len(content.BodySections) > 0 {
		sb.WriteString("- sections: one entry per requested section below, each with the name exactly as given " +
			"and markdown content. Do not invent sections that are not listed. " +
			"Keep this material out of the description; it belongs in its own section.\n")
	} else {
		sb.WriteString("- sections: leave empty; none are requested.\n")
	}

	fmt.Fprintf(&sb, "- title: an imperative-mood subject line naming the change you just described, "+
		"max %d chars, no trailing period. Write the real title; there is no later pass to fix it up.\n",
		content.TitleMaxLength)

	if len(content.BodySections) > 0 {
		sb.WriteString("\nRequested sections:\n")
		writeSectionRequests(&sb, content.BodySections)
	}

	if len(recentCommits) > 0 {
		sb.WriteString("\nMatch the commit message style used in this repository. Here are recent commit titles for reference:\n")
		for _, commit := range recentCommits {
			sb.WriteString("- ")
			sb.WriteString(commit)
			sb.WriteString("\n")
		}
	}
	return sb.String()
}

// writeSectionRequests lists declared sections as a bullet per section.
func writeSectionRequests(sb *strings.Builder, sections []forgeconfig.Section) {
	for _, s := range sections {
		fmt.Fprintf(sb, "- %s", s.Name)
		if s.Required {
			sb.WriteString(" (required)")
		}
		if s.Description != "" {
			sb.WriteString(": ")
			sb.WriteString(s.Description)
		}
		sb.WriteString("\n")
	}
}

// titleStubs are the fillers a model writes when it has to produce a title
// before it knows what to call the change. They are indistinguishable from a
// real title by length, so they need naming explicitly.
var titleStubs = map[string]bool{
	"placeholder":    true,
	"todo":           true,
	"tbd":            true,
	"title":          true,
	"subject":        true,
	"summary":        true,
	"commit title":   true,
	"commit message": true,
	"n/a":            true,
	"none":           true,
	"untitled":       true,
}

// stubTitle reports whether a title is filler rather than a description of the
// change. Leading and trailing punctuation is stripped before matching, so a
// stub that trails structural JSON characters — the model trying to abandon its
// answer and start over, which constrained generation renders as literal text
// inside the string — is recognised as the same thing.
func stubTitle(title string) bool {
	norm := strings.ToLower(strings.TrimFunc(title, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	}))
	return titleStubs[norm]
}

// summaryProblems lists what is wrong with a returned summary in the words the
// model needs to fix it. An empty result means the summary is usable.
//
// Only three things are worth a second call: a title that does not name the
// change, a title over the configured budget, and a required section that came
// back missing or empty. All are cheap to state and cheap to fix, and none can
// be corrected on the host without inventing text.
func summaryProblems(s AgentSummary, content forgeconfig.Content) []string {
	var problems []string

	title := strings.TrimSpace(s.Title)
	switch {
	case title == "":
		problems = append(problems, "the title is empty")
	case stubTitle(title):
		problems = append(problems, fmt.Sprintf(
			"the title %q is a placeholder rather than a description of the change", title))
	}

	if n := len([]rune(title)); n > content.TitleMaxLength {
		problems = append(problems, fmt.Sprintf(
			"the title is %d characters; it must be at most %d", n, content.TitleMaxLength))
	}

	for _, declared := range content.BodySections {
		if !declared.Required {
			continue
		}
		if strings.TrimSpace(sectionContent(s.Sections, declared.Name)) == "" {
			problems = append(problems, fmt.Sprintf(
				"the required section %q is missing or empty", declared.Name))
		}
	}
	return problems
}

// retryPrompt asks for a corrected summary, naming what was wrong.
func retryPrompt(problems []string) string {
	var sb strings.Builder
	sb.WriteString("That summary cannot be used:\n")
	for _, p := range problems {
		sb.WriteString("- ")
		sb.WriteString(p)
		sb.WriteString("\n")
	}
	sb.WriteString("\nProduce the whole summary again, corrected. Keep everything else as it was.")
	return sb.String()
}

// renderBody assembles the shared body that becomes both the commit message
// body and the pull request description: the description first, then each
// declared section under its own heading.
//
// Sections render in the order they were declared, not the order they came
// back in, so the shape of a body is the repository's decision rather than the
// model's. Sections the agent returned that nobody asked for are dropped.
func renderBody(description string, declared []forgeconfig.Section, got []SummarySection) string {
	body := strings.TrimSpace(description)
	for _, d := range declared {
		content := strings.TrimSpace(sectionContent(got, d.Name))
		if content == "" {
			if !d.Required {
				continue
			}
			content = notProvided
		}
		if body != "" {
			body += "\n\n"
		}
		body += "## " + d.Name + "\n\n" + content
	}
	return body
}

// sectionContent finds a returned section by name, matched case-insensitively
// so a model that title-cases a heading still lands in the right slot.
func sectionContent(sections []SummarySection, name string) string {
	for _, s := range sections {
		if strings.EqualFold(strings.TrimSpace(s.Name), strings.TrimSpace(name)) {
			return s.Content
		}
	}
	return ""
}

// ApplyFooter appends the operator's footer to a pull request body. The footer
// is pull-request only: the commit carries trailers instead, which is where git
// tooling looks for this kind of metadata.
func ApplyFooter(body, footer string) string {
	footer = strings.TrimSpace(footer)
	if footer == "" {
		return body
	}
	if body = strings.TrimSpace(body); body == "" {
		return footer
	}
	return body + "\n\n" + footer
}

// ApplyTrailers appends git trailers to a commit message, separated from the
// body by a blank line so `git interpret-trailers` reads them as a trailer
// block.
func ApplyTrailers(message string, trailers []string) string {
	var kept []string
	for _, t := range trailers {
		if t = strings.TrimSpace(t); t != "" {
			kept = append(kept, t)
		}
	}
	if len(kept) == 0 {
		return message
	}
	if message = strings.TrimRight(message, "\n"); message == "" {
		return strings.Join(kept, "\n")
	}
	return message + "\n\n" + strings.Join(kept, "\n")
}
